# Caminho do yt-dlp
script-opts=ytdl_hook-ytdl_path=/home/gbshadow/.local/bin/yt-dlp

# Aceleração por hardware direta via Intel VA-API e OpenGL
vo=gpu
gpu-api=opengl
hwdec=vaapi
profile=fast

# Filtro estrito de formato:
# Prioriza H.264 (avc1) em até 720p (decodificado 100% via hardware pela GPU)
# Bloqueia AV1 e VP9 não suportados em hardware
ytdl-format=bestvideo[height<=?720][vcodec^=avc1]+bestaudio/best[height<=?720][vcodec^=avc1]/bestvideo[height<=?720][vcodec!*=av01]+bestaudio/best[height<=?720][vcodec!*=av01]/best[height<=?720]

# Cache e buffer para reprodução fluida
cache=yes
demuxer-max-bytes=150M
demuxer-max-back-bytes=50M

# Salvar posição de reprodução automaticamente ao fechar
save-position-on-quit=yes
