Net/ThemeName "catppuccin-mocha-blue-standard+default"
Net/IconThemeName "elementary-minios-dark"
Gtk/CursorThemeName "Breeze_Light"
Gtk/CursorThemeSize 32
Gtk/FontName "JetBrainsMono Nerd Font 10"
Gtk/ToolbarStyle "both-horiz"
Gtk/ToolbarIconSize 3
Gtk/ButtonImages 1
Gtk/MenuImages 1
Gtk/EnableAnimations 1
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
Gtk/ApplicationPreferDarkTheme 1
Net/EnableEventSounds 1
Net/EnableInputFeedbackSounds 1
